# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83dd7a27e499ac027eab23f00a570b71eb1f2fd0be6338034166d02ebfe3b1f5090202e95b017b7734b454e26daedc22329883b097839b1c0ab5d4a18ccca568

test:
  secret_key_base: 4a556abb817be9ec3916d3a157e51f6908db58b06980db3418ee3d7a78ddbbf2ebd680c1312f697a87c7be28f1f891a11f17424affc5f4aed107a9d20b2b3d04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
